services:
  myProm:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - localprom
  myNodeExporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100
    restart: unless-stopped
    depends_on:
      - myProm
networks:
  localprom:
    driver: bridge
volumes:
  prom_data: