version: '3.8'
services:
  myProm:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./:/etc/prometheus
      - prom_data:/prometheus
volumes:
  prom_data: